### ISSUE TITLE
incorrect parsing of loudnorm output

### ISSUE THREAD

**Issue by tari3x** [kevinlekiller/mkvrg#9]
The trackPeak regex is currently "Input True Peak: -?[0-9.]+ dBTP", but both ffmpeg 4.4 and current github tip seem to include a + in front of positive values e.g.  
```
 'Parsed_loudnorm_0 @ 0x3b9c100] Input Integrated: -8.9 LUFS Input True Peak: +1.9 dBTP Input LRA: 5.0 LU Input Threshold: -19.0 LUFS Output Integrated: -23.0 LUFS Output True Peak: -8.7 dBTP Output LRA: 3.7 LU Output Threshold: -33.0 LUFS Normalization Type: Dynamic Target Offset: -1.0 LU '
```

This regex seems to work: "Input True Peak: [-\+]?[0-9.]+ dBTP".

**Comment by tari3x** [comment]
Wouldn't it be great if ffmpeg could provide this in some structured form?

**Comment by WhitePeter** [comment]
Should be fixed with https://github.com/kevinlekiller/mkvrg/commit/fab3ce6dea53d940d723a19f7762cdde0daac547.

**Comment by WhitePeter** [comment]
Forgot to close.
